#!/bin/sh

export ELECTRO_CONFIG=/DEMO/evl/Electro/config
export ELECTRO_BIN=/DEMO/evl/Electro/bin

mpirun -machinefile $ELECTRO_CONFIG/nico11x5.dat -np 29 $ELECTRO_BIN/electro-mpi -f $ELECTRO_CONFIG/11x5.lua $@
