#!/bin/sh

#export ELECTRO_CONFIG=/usr/local/Electro/config
#export ELECTRO_BIN=/usr/local/Electro/bin
export ELECTRO_CONFIG=/home/evl/rlk/src/electro/trunk/config
export ELECTRO_BIN=/home/evl/rlk/src/electro/trunk

mpirun -machinefile $ELECTRO_CONFIG/nico.dat -np 9 $ELECTRO_BIN/electro-mpi $ELECTRO_CONFIG/nico.lua $@
