#!/bin/sh

export ELECTRO_CONFIG=/home/rlk/src/electro/trunk/config
export ELECTRO_BIN=/home/rlk/src/electro/trunk

mpirun -machinefile $ELECTRO_CONFIG/zod.dat -np 5 $ELECTRO_BIN/electro-mpi $ELECTRO_CONFIG/zod.lua $@
