#!/bin/sh

export ELECTRO_CONFIG=/usr/local/Electro/config
export ELECTRO_BIN=/usr/local/Electro/bin

mpirun -machinefile $ELECTRO_CONFIG/nico.dat -np 17 $ELECTRO_BIN/electro-mpi $ELECTRO_CONFIG/nico.lua $@
