#!/bin/sh

#export ELECTRO_CONFIG=/usr/local/Electro/config
#export ELECTRO_BIN=/usr/local/Electro/bin
export ELECTRO_CONFIG=/home/evl/rlk/src/electro/config
export ELECTRO_BIN=/home/evl/rlk/src/electro

mpirun -machinefile $ELECTRO_CONFIG/yorda11x5.dat -np 21 $ELECTRO_BIN/electro-mpi -f $ELECTRO_CONFIG/yorda11x5.lua $@
