#!/bin/sh

export ELECTRO_CONFIG=/home/evl/rlk/src/electro/config
export ELECTRO_BIN=/home/evl/rlk/src/electro

mpirun -machinefile $ELECTRO_CONFIG/table.dat -np 10 $ELECTRO_BIN/electro-mpi -f $ELECTRO_CONFIG/table.lua $@
