#!/bin/sh

export ELECTRO_CONFIG=/home/evl/rlk/src/electro-current/config
export ELECTRO_BIN=/home/evl/rlk/src/electro-current

$ELECTRO_BIN/electro $ELECTRO_CONFIG/varrier.lua $ELECTRO_CONFIG/personal-varrier.lua $@
